name: randu_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+2

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.17
  http: ^0.13.5
  shared_preferences_web: ^2.0.0
  provider: ^6.0.5
  get: ^4.1.4
  shimmer: ^2.0.0
  cached_network_image: ^3.1.0+1
  image_picker: ^0.8.6+1
  image_picker_for_web: ^2.1.10
  photo_view: ^0.14.0
  path_provider: ^2.0.1
  url_launcher: ^6.0.0
  sqflite: ^2.0.0+3
  flutter_local_notifications: ^12.0.4
  intl: ^0.18.1
  dropdown_search: ^3.0.1
  flutter_html: ^2.2.1
  flutter_native_splash: ^2.0.0
  sweetalertv2: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.3.0

  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/randu_logo.png"

flutter_native_splash:
  color: "#2F467B"
  #background_image: "assets/background.png"

  image: assets/randu_acc.png

  # branding: assets/dart.png

  #branding_dark: assets/dart_dark.png

  # ios_content_mode value.
  # branding_mode: bottom

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  android: true
  ios: true
  web: false

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #To add assets to your application, add an assets section, like this:
  assets:
    - images/login.png
    - images/randu.png
    - images/jurnal_icon.png
    - images/laporan_icon.png
    - images/pengaturan_icon.png
    - images/penyusutan_icon.png
    - images/utang_icon.png
    - images/exit.png
    - images/kalendar.png
    - images/bukubesar.png
    - images/labarugi.png
    - images/neraca.png
    - images/neracasaldo.png
    - images/hutang.png
    - images/piutang.png
    - images/setting_awal.png
    - images/setting_rekening.png
    - images/setting_open.png
    - images/setting_hapus.png
    - images/randu_akuntansi.png
    - images/randu_acc.png
    - images/randu_icon.png
    - images/excel_icon.png
    - images/pdf_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: PoppinsBold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf

    - family: PoppinsSemi
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: PoppinsItalic
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf

    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf

    - family: RubikBold
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf

    - family: RubikLight
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf

    - family: RubikMedium
      fonts:
        - asset: assets/fonts/Rubik-Medium.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
